### ISSUE TITLE
XML Hatası

### ISSUE THREAD

**Issue by velet** [msbeden/mutlucellsms#1]
Test etmek istediğim zaman bu hatayı aldım hocam. sadece api bilgileri girildi bir değişiklik yapılmadı.
Post edilen xml eksik veya hatalı.

**Comment by msbeden** [comment]
Hata giderilmiştir. htmlentities() den kaynaklı Türkçe karakterlerden doğan bir sorun mevcuttu.

**Comment by velet** [comment]
Teşekkürler Hocam :)
